spring:
  datasource:
    url: jdbc:mysql://211.254.215.146:65000/ptpt
    username: ptpt_user
    password: ptpt@user138
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.flywaydb: DEBUG
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
    com.example.fitmate: DEBUG


# 서버 포트 설정
server:
  port: 9090

# Swagger UI 설정
springdoc:
#  server-url: https://ptpt.ngrok.app
  server-url: https://e9d2-59-8-4-136.ngrok-free.app
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# jwt key(test 용, env 로 이동)
jwt:
  secret: 7KAwWI4D6wbwSZ4IdUsrikAbrrwBJaIsZInN7YfE1WXaS4bep7p6eZGPi4MBNFYd

  # 10 min: 10min * 60 sec * 1000 millisecond
  # 10800000 3 hours: 3hours * 60min * 60sec * 1000 millisecond

ptpt:
  upload:
    # feed 이미지 설정(기존)
    urlPrefix:  /feeds/images/
    imagePath:  classpath:img/feed

    # profile 이미지 설정(추가)
    profileUrlPrefix:  /profiles/images/
    profileImagePath:  classpath:img/profile